spring.datasource.url=jdbc:mysql://localhost:3306/vehicleSpare?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=acpt
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



file.upload-dir=C:/Users/adhee/Desktop/myproject/spareparts-backend/uploads
